name: community_frontend
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get: ^4.6.6
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  intl: ^0.18.1
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  share_plus: ^7.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
